baseURL: "https://insideseek.netlify.app"
languageCode: en-us
title: Inside Seek
theme: PaperMod

params:
  homeInfoParams:
    title: "Hello, Inside Seekers!"
    content: "Explore the world of Software Development, Technology Trends, and Coding Insights. Join us on this journey to stay updated and inspired!"
  
  author: Stockson
  ShowReadingTime: true
  ShowShareButtons: true
  
  socialIcons:
    - name: GitHub
      url: "https://github.com/insideseek/"
    - name: Twitter
      url: "https://twitter.com/insideseek/"
    - name: Pinterest
      url: "https://pinterest.com/insideseek/"

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: newsletter
      name: Newsletter
      url: /newsletter/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
    - identifier: privacy
      name: Privacy
      url: /privacy/
      weight: 5